### ISSUE TITLE
适应忽略元素进行地图忽略位置偏移的问题

### ISSUE THREAD

**Issue by liangyuan1** [LarryZhu-dev/autofit.js#20]
虽然忽略可以解决点击位置偏移的问题，但是会导致地图中心点整体向右偏移，在低分辨下偏移更严重

**Comment by LarryZhu-dev** [comment]
这是为了兼容非地图元素回放导致的，若遇到此问题，手动把ignore元素的transform-origin设置为50% 50%即可，后续考虑改进此问题

**Comment by smilebkf** [comment]
设置transform-origin效果不好，如果固定scale地图会充满容器，设置transform-origin不起作用；如果不固定scale，设置transform-origin可以解决地图偏移问题，但是会缩放导致地图无法充满原容器，周围出现白边。
![image](https://github.com/LarryZhu-dev/autofit.js/assets/31026195/8ceb2297-9891-4c3c-9965-ab25b7365ba3)

**Comment by LarryZhu-dev** [comment]
> 虽然忽略可以解决点击位置偏移的问题，但是会导致地图中心点整体向右偏移，在低分辨下偏移更严重

使用 elRectification 可以解决此问题
