### ISSUE TITLE
antd组件没有进行缩放,有什么解决方案吗?

### ISSUE THREAD

**Issue by hwy1010** [LarryZhu-dev/autofit.js#22]
![image](https://github.com/LarryZhu-dev/autofit.js/assets/61402783/d0b56466-c8ba-4d0d-9bc0-cece764d3c6b)

**Comment by LarryZhu-dev** [comment]
如果antd的组件渲染在缩放元素外（比如#app外）则不会触发缩放，看一下挂载在哪里，如果在body内，则可以传autofit.init("body")试一下

**Comment by hwy1010** [comment]
> 如果antd的组件渲染在缩放元素外（比如#app外）则不会触发缩放，看一下挂载在哪里，如果在body内，则可以传autofit.init("body")试一下

改成body确实可以了,但有些antd组件的下拉框会出现偏移的情况,这种情况只能手动去更改样式了是吧?

**Comment by LarryZhu-dev** [comment]
因为每个UI库对于插入元素的位置计算逻辑不同，所以我也不能确定它的位置偏移是什么原因，参考问题： #6
