### ISSUE TITLE
echarts 图标偏移问题

### ISSUE THREAD

**Issue by yijia0723** [LarryZhu-dev/autofit.js#23]
echarts 图标偏移问题

**Comment by LarryZhu-dev** [comment]
请告诉我： 出现场景和复现步骤、现象截图和描述、代码片段

**Comment by yijia0723** [comment]
![image](https://github.com/LarryZhu-dev/autofit.js/assets/104214378/e16ff166-abee-42f8-9d63-f420b81a9f43)
缩小屏幕图标就偏位了

**Comment by LarryZhu-dev** [comment]
对于element定位元素支持不佳是已知问题，正在尽力解决中
你可以尝试ignore或elRectification，如果不能解决问题，请等待后续修复

**Comment by LarryZhu-dev** [comment]
echarts 宽高应为 100% ，并在缩放时 resize
