### ISSUE TITLE
缩放会导致 table 的单元格出现间隙

### ISSUE THREAD

**Issue by Arthre** [LarryZhu-dev/autofit.js#29]
`transform: scale(1.896);` 后会导致单元格有白边。
已经使用使用 `border-collapse: collapse;` 合并了边框。

复现DEMO地址： https://codesandbox.io/s/autofit-demo-pkgzc6?file=/src/App.vue

**Comment by LarryZhu-dev** [comment]
收到反馈，但这个问题我留意已久，没有发现解决办法。其实不只是缩放会导致这个问题，使用任何transform值都可能导致这个问题，暂时无法修复。

**Comment by Arthre** [comment]
好吧，感谢反馈 👍

**Comment by Adaer** [comment]
白线是table的颜色，看看设置table的背景色能否解决问题

**Comment by LarryZhu-dev** [comment]
@Adaer 其实不光是table ，我之前写 div 用transform熟悉也会导致这个问题，当然修改底色可以解决
