### ISSUE TITLE
Cannot read properties of undefined (reading 'isAutofitRunnig')

### ISSUE THREAD

**Issue by Kristineberg** [LarryZhu-dev/autofit.js#34]
想通过elRectification来忽略地图容器，但是报错：Cannot read properties of undefined (reading 'isAutofitRunnig')

```js
onMounted(() => {
  elRectification('#map');
});
```

使用ignore忽略地图容器，会造成地图显示不全，容器宽度设置的都是100%，请问使用elRectification是否可以解决这问题，不忽略的话地图会显得很模糊

**Comment by LarryZhu-dev** [comment]
对不起，这是3.0.5版本bug，请退回3.0.4使用该功能

**Comment by Kristineberg** [comment]
> 对不起，这是3.0.5版本bug，请退回3.0.4使用该功能

好哒 我回退试试，我以为是我代码问题 试了半天哈哈哈

**Comment by Kristineberg** [comment]
> 对不起，这是3.0.5版本bug，请退回3.0.4使用该功能

大佬，3.0.4也报Cannot read properties of undefined (reading 'isAutofitRunnig')这个错，回退3.0.3版本，elRectification使用正常，但是非全屏状态下，页面显示不全，3.0.5版本是好的

![image](https://github.com/LarryZhu-dev/autofit.js/assets/115999728/2579f336-60e0-4b2d-8bc1-1e8d7ee2e0a8)

**Comment by LarryZhu-dev** [comment]
刚刚已更新 3.0.6 🤣

**Comment by Kristineberg** [comment]
> 刚刚已更新 3.0.6 🤣

卧槽大佬牛逼 发现居然没star 抽自己一下 立马star！！！

**Comment by LarryZhu-dev** [comment]
@Kristineberg 这个功能前几天刚加上，没测试完全，正好刚刚在看邮箱，看到你的问题，发现我擦果然不对，就顺手改了下，谢谢你反馈好兄弟，谢谢你star，好用给兄弟推一下

**Comment by Kristineberg** [comment]
> @Kristineberg 这个功能前几天刚加上，没测试完全，正好刚刚在看邮箱，看到你的问题，发现我擦果然不对，就顺手改了下，谢谢你反馈好兄弟，谢谢你star，好用给兄弟推一下

必须推！我要疯狂安利给小伙伴，市面上好多自适应组件挨个试了一遍，都没你这好使，大佬威武！！

**Comment by LarryZhu-dev** [comment]
😄🥳

**Comment by LarryZhu-dev** [comment]
> 必须推！我要疯狂安利给小伙伴，市面上好多自适应组件挨个试了一遍，都没你这好使，大佬威武！！

😄🥳
