### ISSUE TITLE
echart 显示 tooltip 造成界面模糊

### ISSUE THREAD

**Issue by TZTMAXz** [LarryZhu-dev/autofit.js#35]
![1700188965231](https://github.com/LarryZhu-dev/autofit.js/assets/52589283/68553bce-ba9e-4c42-b5ba-c8ca99cf1cc8)
把 tooltip 悬浮框添加在 body 中就不会出现这个问题
![1700189187646](https://github.com/LarryZhu-dev/autofit.js/assets/52589283/bff87495-8ef7-4de8-9e18-d64fe0d8c51e)

**Comment by TZTMAXz** [comment]
![1700189317090](https://github.com/LarryZhu-dev/autofit.js/assets/52589283/b01c7810-9158-4e5a-982e-8342f0e581e1)

**Comment by LarryZhu-dev** [comment]
造成模糊的原因和 element 部分弹窗组件定位偏移属于同一问题，你的处理方法没错，element 也有相关属性，将元素添加到body里可以解决此问题
<img width="913" alt="bbce26d04e1b80c228db189e092d98b" src="https://github.com/LarryZhu-dev/autofit.js/assets/40397402/eb748899-d3cb-4c71-bb56-fa24b27a0a1d">
