### ISSUE TITLE
使用插件后导致宽度被默认设置为 2171.31px

### ISSUE THREAD

**Issue by huangbaishui** [LarryZhu-dev/autofit.js#36]
![image](https://github.com/LarryZhu-dev/autofit.js/assets/138289944/8982c2ea-db68-429c-b002-4a93f5f684af)
![image](https://github.com/LarryZhu-dev/autofit.js/assets/138289944/fa815443-9851-4be2-9956-3076b19c68e5)
![image](https://github.com/LarryZhu-dev/autofit.js/assets/138289944/0356ed97-8474-40eb-9e07-c665d261e22c)

**Comment by huangbaishui** [comment]
![image](https://github.com/LarryZhu-dev/autofit.js/assets/138289944/fa407343-0fec-4f2a-be5d-8bebd28daac2)

**Comment by LarryZhu-dev** [comment]
全屏状态下才是 1920*1080，非全屏状态要去除浏览器头，所以会有一些缩放，属于正常现象，可以关注下个版本 ( 预计是v3.0.7 ) 更新，将新增参数，新的参数可以控制 缩放值与 1 比较的阈值，比如设置阈值为 0.2 ，则缩放 <0.8 和 >1.2 时才会缩放，在这个阈值内的则不会触发缩放

**Comment by huangbaishui** [comment]
如果是这样的话, 一个用户展示书签栏, 另一个不展示书签栏 最后的宽度也会不同

**Comment by LarryZhu-dev** [comment]
> 如果是这样的话, 一个用户展示书签栏, 另一个不展示书签栏 最后的宽度也会不同

当然是会不同，不用管宽度多少啊，就问你页面显示正不正常就完了
