### ISSUE TITLE
fullCalendar 自适应失效

### ISSUE THREAD

**Issue by wyf195075595** [LarryZhu-dev/autofit.js#38]
autofit.js 造成 fullCalendar 自适应异常，外部事件拖拽位置偏移
![image](https://github.com/LarryZhu-dev/autofit.js/assets/60338824/fc2aae37-fe2f-4526-81c9-1033c3102542)
### 注释 autofit.init() 就正常
elRectification 方法，本地试了也没有用
[演示地址](https://codepen.io/wyf195075595/pen/qBgYeMd)

**Comment by LarryZhu-dev** [comment]
我试了下，用 elRectification 后，鼠标在单元格中的位置正确了，但是拖拽的项位置是偏移的，这是因为FullCalendar 插件计算拖拽元素的位置时，采用的是实际渲染宽高，而不是元素设置宽高导致的这一问题。如选中元素的witdh被autofit.js设置为2069px，缩放为scale(0.61)，那么实际宽度则是 2069px*0.61 = 1262.09，这样就会出现 你拖动元素时，鼠标到了最右侧(2069px)时，元素只会移动到1262.09，高度上也是同理。
目前看 autofit.js 采用的方案无法解决这个问题，你可以去FullCalendar下提个issues，看看他们能不能解决。
