### ISSUE TITLE
如果一个元素，在init之前是display none的，有没有add的方法将其加入自适应

### ISSUE THREAD

**Issue by zhengdechang** [LarryZhu-dev/autofit.js#39]
如果一个元素，在init之前是display none的，有没有add的方法将其加入自适应，比如antd的select组件，下拉前是不存在body中的，点开下拉后，和select的元素width没有同宽

**Comment by LarryZhu-dev** [comment]
如果元素在 缩放元素内部 ，比如 autofit.init("body") ，display none的元素在body内，则 display block 时它也会跟随缩放的，你所提到的情况应该是antd没有把元素挂载到Body内部，你可以看下antd的文档，看是否有挂载到body的选项，我看element有的组件有这个属性

**Comment by zhengdechang** [comment]
我已经将下拉框挂在到selec上了，依然是不行，如果autofit绑定到html，则下拉框的定位有问题

**Comment by LarryZhu-dev** [comment]
你的select组件没有在Body上
