### ISSUE TITLE
页面内引入dialog组件页面会导致页面缩小

### ISSUE THREAD

**Issue by yurongfa** [LarryZhu-dev/autofit.js#40]
![Snipaste_2023-11-27_11-56-58](https://github.com/LarryZhu-dev/autofit.js/assets/128275436/283336a4-2beb-4929-944f-cd4793ac2183)
大佬，再页面内引入dialog组件页面会导致页面缩小，啥情况？我看了掘金上面的文章和评论区尝试了一些方法，均未生效。

**Comment by LarryZhu-dev** [comment]
不支持element哈，有些组件有挂载到body的属性，但是对于dialog这种会影响大容器的东西，我这边也无能为力啊，建议element和autofit.js不要一起用的哈，后期我会再出一篇文章，单独解释下这方面的问题

**Comment by yurongfa** [comment]
好的好的，非常感谢大佬抽空回复！
