### ISSUE TITLE
element-plus 弹窗异常

### ISSUE THREAD

**Issue by wyf195075595** [LarryZhu-dev/autofit.js#41]
上次反映的 日历插件问题值不加拖拽功能就还好，这次这个 element-plus 就难受了。 弹窗后会造成页面右侧留白，element-ui 版本弹窗没有这个问题。
[演示地址](https://codepen.io/wyf195075595/pen/JjxBdwE?editors=1100)

**Comment by wyf195075595** [comment]
项目里边用的时候是浏览器 缩放<= 100% 没有问题，>100% 就出现这个问题了

**Comment by LarryZhu-dev** [comment]
element 弹窗会强制计算屏幕大小，这样就覆盖了 autofit.js 的设置，很多时候autofit.js 都不能和autofit.js很好的契合，建议使用element时不要使用autofit.js了🤡

**Comment by wyf195075595** [comment]
害，没法子。只能用 rem 了。感谢大佬解惑

**Comment by LarryZhu-dev** [comment]
不用客气，有机会再用吧，感谢支持
