### ISSUE TITLE
出现留白

### ISSUE THREAD

**Issue by chenJJ-88** [LarryZhu-dev/autofit.js#43]
我配置后出现留白的情况呢
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/571bdbf9-3e46-443c-81ef-d6f9d86baf7d)
下面是我配置的代码：
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/26405c64-5c35-4a22-a8b0-37341983fef8)
下面是我的全局文件挂载的dom节点，也就是在 #root 上，
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/b4dcb8bf-6cb6-4c2e-96ed-4c1212cc2ffa)
请大佬帮忙解惑呢

**Comment by chenJJ-88** [comment]
我在这个盒子上宽高也是写死的
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/5ae44137-6d17-4484-993d-105ce626280c)
不知道这样hu会有影响吗

**Comment by LarryZhu-dev** [comment]
看你写的是body，但是body上没有看到autofit.js设置的样式，内部元素也不要定死，写100%即可

**Comment by chenJJ-88** [comment]
> 看你写的是body，但是body上没有看到autofit.js设置的样式，内部元素也不要定死，写100%即可

请问一下，我不用body，写root为节点，内部也写成了100%
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/1e6cbedb-b231-4248-bf04-8060e91ae9c7)
他是缩放了，但是内部很多模块并没有随之缩放，
这是我的原来的样子，我使用用插件后变成了这样：
![image](https://github.com/LarryZhu-dev/autofit.js/assets/118970817/1c935d66-47b4-4f73-bb59-4afde21e6a0c)
插件不会去scale 放大他们吗？

**Comment by LarryZhu-dev** [comment]
> > 看你写的是body，但是body上没有看到autofit.js设置的样式，内部元素也不要定死，写100%即可
> 
> 请问一下，我不用body，写root为节点，内部也写成了100% ![image](https://private-user-images.githubusercontent.com/118970817/287641205-1e6cbedb-b231-4248-bf04-8060e91ae9c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjA4MzksIm5iZiI6MTcwMTc2MDUzOSwicGF0aCI6Ii8xMTg5NzA4MTcvMjg3NjQxMjA1LTFlNmNiZWRiLWIyMzEtNDI0OC1iZjA0LTgwNjBlOTFhZTljNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDkxOWI3M2Q5YWNmOTE4OGVmNGQ3M2YxNTU1NjgzZjFhYTcyNmY5MWQwNDc3MDg3ZmUzYTFjMmFlN2FkYzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P4eHhuFu7ZFxlAJ2hx0H-EyB4kNsTkwEAlydFUqYeyQ) 他是缩放了，但是内部很多模块并没有随之缩放， 这是我的原来的样子，我使用用插件后变成了这样： ![image](https://private-user-images.githubusercontent.com/118970817/287643130-1c935d66-47b4-4f73-bb59-4afde21e6a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjA4MzksIm5iZiI6MTcwMTc2MDUzOSwicGF0aCI6Ii8xMTg5NzA4MTcvMjg3NjQzMTMwLTFjOTM1ZDY2LTQ3YjQtNGY3My1iYjU5LTRhZmRlMjFlNmEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjYzZDZmNmY3NzYzMTU3YjlmOGM1YzkwOTFiZWY0NGE5ODU2MjBmODVhMTc2MmZiZWFkOWRiNTFiZDQxNmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GtaBUBuLQQOKL5Pw_9rvE0ZRVzv75hHX-IzTnoXzEag) 插件不会去scale 放大他们吗？

内部元素也需要百分比，定死宽高虽然会缩放，但是也会填不满父级元素

**Comment by chenJJ-88** [comment]
> > > 看你写的是body，但是body上没有看到autofit.js设置的样式，内部元素也不要定死，写100%即可
> > 
> > 
> > 请问一下，我不用body，写root为节点，内部也写成了100% ![image](https://private-user-images.githubusercontent.com/118970817/287641205-1e6cbedb-b231-4248-bf04-8060e91ae9c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjA4MzksIm5iZiI6MTcwMTc2MDUzOSwicGF0aCI6Ii8xMTg5NzA4MTcvMjg3NjQxMjA1LTFlNmNiZWRiLWIyMzEtNDI0OC1iZjA0LTgwNjBlOTFhZTljNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDkxOWI3M2Q5YWNmOTE4OGVmNGQ3M2YxNTU1NjgzZjFhYTcyNmY5MWQwNDc3MDg3ZmUzYTFjMmFlN2FkYzZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P4eHhuFu7ZFxlAJ2hx0H-EyB4kNsTkwEAlydFUqYeyQ) 他是缩放了，但是内部很多模块并没有随之缩放， 这是我的原来的样子，我使用用插件后变成了这样： ![image](https://private-user-images.githubusercontent.com/118970817/287643130-1c935d66-47b4-4f73-bb59-4afde21e6a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjA4MzksIm5iZiI6MTcwMTc2MDUzOSwicGF0aCI6Ii8xMTg5NzA4MTcvMjg3NjQzMTMwLTFjOTM1ZDY2LTQ3YjQtNGY3My1iYjU5LTRhZmRlMjFlNmEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwNzE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjYzZDZmNmY3NzYzMTU3YjlmOGM1YzkwOTFiZWY0NGE5ODU2MjBmODVhMTc2MmZiZWFkOWRiNTFiZDQxNmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GtaBUBuLQQOKL5Pw_9rvE0ZRVzv75hHX-IzTnoXzEag) 插件不会去scale 放大他们吗？
> 
> 内部元素也需要百分比，定死宽高虽然会缩放，但是也会填不满父级元素

那字体这些都是需要写成rem这种吗，缩放也不会生效吗？

**Comment by LarryZhu-dev** [comment]
@chenJJ-88 不是，不支持任何相对单位，包括rem\vh\vw等

**Comment by chenJJ-88** [comment]
> @chenJJ-88 不是，不支持任何相对单位，包括rem\vh\vw等

但是我看我开启后，字体大小还是我写死的那么大，并没有随之放大呢
