### ISSUE TITLE
地图叠加完点popup会有偏移

### ISSUE THREAD

**Issue by wanglingwen666** [LarryZhu-dev/autofit.js#44]
![image](https://github.com/LarryZhu-dev/autofit.js/assets/73384505/9c2dcaf5-ea2a-45a0-83ae-48328454a21e)
![image](https://github.com/LarryZhu-dev/autofit.js/assets/73384505/c2a4f178-ebbe-4bf9-a0bd-c68484335bdf)
![image](https://github.com/LarryZhu-dev/autofit.js/assets/73384505/6daf851e-6ce5-4325-8c30-eb57dc2f52cc)
默认popup实在该点位置上，请问有办法解决吗？

**Comment by LarryZhu-dev** [comment]
ignore
