### ISSUE TITLE
用了button按钮点击后会出现灰色遮罩

### ISSUE THREAD

**Issue by quannpc** [LarryZhu-dev/autofit.js#49]
我是vue2项目，我在app组件上用了所有button按钮点击后会出现灰色遮罩
mounted() {
		autofit.init(
			{
				dh: 1080,
				dw: 1920,
				el: "#routerview-box",
				resize: true,
				ignore: [
					{
						el: ".gaodeMap",
					},
				],
			},
			false
		);
	},
beforeDestroy() {
		autofit.off();
	},

我用了下面的形式就没有了，不知道上面的形式是什么原因
mounted() {
		autofit.init({
			designHeight: 1080,
			designWidth: 1920,
			renderDom: "#app",
			resize: true,
		});
	},

	beforeDestroy() {
		autofit.off();
	},

**Comment by LarryZhu-dev** [comment]
可以提供一个复现示例吗

**Comment by quannpc** [comment]
可以，我给评论的里面有两段代码，你可以分别用在App文件里，看一下是不是，我用的是若依，element-ui，不知道其他会不会有这个情况



在 2023-12-21 16:59:38，"Larry Zhu" ***@***.***> 写道：

可以提供一个复现示例吗
