### ISSUE TITLE
手动缩放浏览器可以正常适应，点击最大化（或F11全屏）时却失效了

### ISSUE THREAD

**Issue by MaboZZZ** [LarryZhu-dev/autofit.js#50]
keepFit函数中let height = Math.round(clientHeight / currScale);let width = Math.round(clientWidth / currScale);如果currScale缩放比例是小于1的话，那缩小的情况下宽高不是更大了吗？不知道是不是这个原因导致的

**Comment by MaboZZZ** [comment]
用的是dom.requestFullscreen相关函数全屏的

**Comment by LarryZhu-dev** [comment]
版本是多少

**Comment by wangping1408** [comment]
使用3.1.0版本，F11全屏下可以正常适应，但是在dom.requestFullscreen下失效了
