### ISSUE TITLE
宽度和高度不能沾满

### ISSUE THREAD

**Issue by SHEN-EN** [LarryZhu-dev/autofit.js#51]
![1704272634010](https://github.com/LarryZhu-dev/autofit.js/assets/37680708/047e7b0c-17c9-495f-8644-cfd8ee2e1848)
这个是我没有全屏的样子 

![1704272736991](https://github.com/LarryZhu-dev/autofit.js/assets/37680708/650c1595-4a55-49e9-a139-e525e725ba8a)

这个是我全屏的样子

没有全屏的时候宽度没有沾满 
全屏的时候高度没有沾满

**Comment by LarryZhu-dev** [comment]
自查样式
