### ISSUE TITLE
设置后，高度无法占满，留有一部分白

### ISSUE THREAD

**Issue by Quinlivanner** [LarryZhu-dev/autofit.js#52]
`  mounted() {
    autofit.init({
      dh: "1080",
      dw: "1920",
      el: "#app",
      resize: true,
    });
  },`

这样设置，正常缩放，但是底部有留白，我的 Page 高度设置为 100vh，占不满

<img width="1920" alt="截屏2024-01-05 13 57 52" src="https://github.com/LarryZhu-dev/autofit.js/assets/68963063/07fb5eaf-7460-4535-b828-beac5d3f06c3">

**Comment by LarryZhu-dev** [comment]
设置为100%
