### ISSUE TITLE
input 文本框聚焦会变模糊

### ISSUE THREAD

**Issue by TZTMAXz** [LarryZhu-dev/autofit.js#57]
![input](https://github.com/LarryZhu-dev/autofit.js/assets/52589283/fcf96aa4-3806-417b-8e85-839b68d37f05)

**Comment by LarryZhu-dev** [comment]
scale方案无法避免此问题

**Comment by TZTMAXz** [comment]
> scale方案无法避免此问题

是什么原因造成的呢

**Comment by LarryZhu-dev** [comment]
@TZTMAXz 看一下这个哈：https://juejin.cn/post/7066986698575446030
