### ISSUE TITLE
针对于 ignore 属性是否存在优化项

### ISSUE THREAD

**Issue by topazur** [LarryZhu-dev/autofit.js#58]
目前：
<img width="438" alt="image" src="https://github.com/LarryZhu-dev/autofit.js/assets/88650465/7e20ed4d-be01-4f53-867e-33af4e66c25f">
期望：
<img width="459" alt="image" src="https://github.com/LarryZhu-dev/autofit.js/assets/88650465/7cb71527-3f87-456d-9196-4cfb59ca43ab">

目前支持 `同时缩放xy轴`，我期望 ignore 可以支持 `仅缩放x轴`、`仅缩放y轴`。为了兼容老api，增加 ignoreX 和 ignoreY 来实现，你觉得怎么样？（我不确定我的使用是否正确，这是就目前情况来看我的想法）

**Comment by LarryZhu-dev** [comment]
好主意，我近期会评估一下，如果这是个有必要的升级，我会考虑在下个版本新增你说的参数功能

**Comment by topazur** [comment]
## 对象形式设置wdith:100%;
<img width="1035" alt="image" src="https://github.com/LarryZhu-dev/autofit.js/assets/88650465/84080c25-75e0-477b-b9db-1a116d7c3fd1">

## 刚看了源码发现ignore可以传递对象，设置width为百分百后超出了容器，还是不符合预期，还是要从scale上处理
> 不过可以不用加api了，直接通过 ignore 的对象格式细分支持 scaleX 和 scaleY 属性即可
<img width="886" alt="image" src="https://github.com/LarryZhu-dev/autofit.js/assets/88650465/47391c75-366b-4fc8-8d1e-79eb1ee8474b">

## 解决
```diff
for (let item of ignore) {
- let realScale = item.scale ? item.scale : 1 / currScale;
// case1: 此处可以增加 sacleX 或者 scaleY
// case2: scale支持数组格式，空值被 1 / currScale 填充
```

**Comment by LarryZhu-dev** [comment]
是的，这种用法我自己都没有想到，🤡！，厉害厉害
