### ISSUE TITLE
使用transform: scale(0.465104); 会对页面el-dialog的蒙版影响

### ISSUE THREAD

**Issue by gaowen0908** [LarryZhu-dev/autofit.js#6]
使用transform: scale(0.465104); 会对页面el-dialog的蒙版影响，蒙版把元素当下面了，这个有解决办法么？

**Comment by 995231030** [comment]
这个目前没想到好的解决办法，transform无论任何属性都会造成内部子元素定位以其为基准。方便贴一下代码片段吗？看看有没有好的解决方案

**Comment by gaowen0908** [comment]
https://github.com/995231030/autofit.js/assets/41286207/9817b507-95ad-433a-b8b8-ba91caadbfd6
蒙版在所选元素#app外面了，就会出现这个问题，如果添加到app元素内没问题
https://github.com/995231030/autofit.js/assets/41286207/35682736-a0ae-4ed6-bd8b-db6d349dd838
如果这个属性设置为false，也是可以的，但是项目有好多用到这个组件，看看是否有方法可以全局设置这个属性

**Comment by 995231030** [comment]
目前建议是先自己单抽离出一个组件，然后用自己的组件，我这边再研究研究，看看怎么解决这个问题

**Comment by gaowen0908** [comment]
OK

**Comment by alphabetabc** [comment]
在app下面声明一个div 放modal的container
![image](https://github.com/LarryZhu-dev/autofit.js/assets/29876424/39d9024c-69e5-4d5c-87ce-d8234e02ce23)

**Comment by ldw0810** [comment]
> 在app下面声明一个div 放modal的container ![image](https://user-images.githubusercontent.com/29876424/273485002-39d9024c-69e5-4d5c-87ce-d8234e02ce23.png)

这个办法好，点个赞

**Comment by LarryZhu-dev** [comment]
在app下面声明一个div 放modal的container有可能是可行的，但是element不是所有组件都支持这个属性，我还发现很多组件有各种各样的问题，建议大家用第三方组件库的话还是打消使用autofit.js的念头吧，我自己都不用😄，其实它还是适合大屏或者纯自研的项目。

**Comment by xu-Aurora** [comment]
> 在app下面声明一个div 放modal的container有可能是可行的，但是element不是所有组件都支持这个属性，我还发现很多组件有各种各样的问题，建议大家用第三方组件库的话还是打消使用autofit.js的念头吧，我自己都不用😄，其实它还是适合大屏或者纯自研的项目。

按你这个说法，可以设置使用的ui库的话不需要autofit.js做适配嘛？比如我使用了element，element所有组件的样式都忽略autofit.js适配，只有自己写的样式才走autofit.js适配

**Comment by LarryZhu-dev** [comment]
> > 在app下面声明一个div 放modal的container有可能是可行的，但是element不是所有组件都支持这个属性，我还发现很多组件有各种各样的问题，建议大家用第三方组件库的话还是打消使用autofit.js的念头吧，我自己都不用😄，其实它还是适合大屏或者纯自研的项目。
> 
> 按你这个说法，可以设置使用的ui库的话不需要autofit.js做适配嘛？比如我使用了element，element所有组件的样式都忽略autofit.js适配，只有自己写的样式才走autofit.js适配

不是，我意思有modal这个属性的可以正确跟随autofit.js的设置缩放，其他的不支持这个属性的，autofit.js无能为力

**Comment by k983551019** [comment]
男蹦

> 在app下面声明一个div 放modal的container有可能是可行的，但是element不是所有组件都支持这个属性，我还发现很多组件有各种各样的问题，建议大家用第三方组件库的话还是打消使用autofit.js的念头吧，我自己都不用😄，其实它还是适合大屏或者纯自研的项目。

难蹦😭
