### ISSUE TITLE
作者能否提供umd版本的,好像没有提供,只有esm版本的

### ISSUE THREAD

**Issue by iamzzg** [LarryZhu-dev/autofit.js#62]
作者能否提供umd版本的,好像没有提供,只有esm版本的

**Comment by LarryZhu-dev** [comment]
不在计划内，感谢支持

**Comment by iamzzg** [comment]
作者不考虑直接通过script标签引入您这个库的用户的话(比如我这种用户),倒也无伤大雅,只不过一般的js库有提供umd版本的一般都会有提供.不然只能靠用户自己fork配置多umd输出方式的打包了,但其实是会流失一部分用户的我觉得,个人拙见(*￣▽￣*)ブ.
