### ISSUE TITLE
请问支持IE浏览器吗

### ISSUE THREAD

**Issue by lztbwlkj** [LarryZhu-dev/autofit.js#63]
请问支持IE浏览器吗？IE9以上的浏览器

**Comment by LarryZhu-dev** [comment]
目前已知全浏览器支持。
参阅：https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform-function/scale#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7
