### ISSUE TITLE
希望能提供zoom缩放样式可选

### ISSUE THREAD

**Issue by qishenliang** [LarryZhu-dev/autofit.js#66]
scale方案会导致第三方组件库的弹出层错位，目前测试antv能适配zoom缩放无错位，兼容性看场景

**Comment by LarryZhu-dev** [comment]
好的，评估后会考虑新增此功能

**Comment by LarryZhu-dev** [comment]
> scale方案会导致第三方组件库的弹出层错位，目前测试antv能适配zoom缩放无错位，兼容性看场景

v3.1.2 已支持 该功能 可使用 cssMode:"zoom" 改用 zoom模式
