### ISSUE TITLE
PrimeVue这个UI框架那些弹出层都回出现偏移

### ISSUE THREAD

**Issue by XAllure** [LarryZhu-dev/autofit.js#70]
PrimeVue这个UI框架那些弹出层都会出现偏移，但是如果有appendTo的话，设置为appendTo=”self”的话就没有问题，默认body的话全都有问题，但是tooltip没有这个参数可以设置，不知道这边有没有办法解决。

**Comment by LarryZhu-dev** [comment]
参考 #67
