### ISSUE TITLE
插件没有适配 window.devicePixelRatio

### ISSUE THREAD

**Issue by lky5230** [LarryZhu-dev/autofit.js#73]
插件没有适配 window.devicePixelRatio

**Comment by LarryZhu-dev** [comment]
可以提供一个最小复现案例吗
https://stackblitz.com/

**Comment by lky5230** [comment]
> 可以提供一个最小复现案例吗 https://stackblitz.com/

我描述一下吧
1.我是1920*1080显示屏。
2.如图，
![image](https://github.com/user-attachments/assets/4e706fb5-429e-4d71-ae23-4d8431af05c8)

我的电脑的缩放是125%。
3.启动前端项目，F12打印window.devicePixelRatio显示为1.25。
4.使用插件后，autofit参数设置为1920*1080，按F11全屏，body的transform的scale是0.8，而不是预想的1.0，应该为0.8*1.25。

**Comment by LarryZhu-dev** [comment]
@lky5230 你好，你描述的情况是正常现象，且应该如此。设置系统缩放后，浏览器可视区域宽高会发生实际的 px 变化而不是依据系统缩放去缩放px值的，此时autofit获取到的屏幕宽高不是1920*1080，而是变化后的实际px值，为了达到显示效果，即使全屏时也会有缩放（因为屏幕宽高和设计宽高依然不同），如果还有问题，请继续留言
